### PR TITLE
README.md: Clarify incompatibility of cheap Aliexpress FPC connectors

### PR DESCRIPTION
**Pull request by rah2501**
This one sentence in the README.md cost me a bunch of time, money, wasted components and possibly a whole PCB.  One is not amused.

### CODE REVIEW

**Comment by DmNosachev** [comment]
I'm sorry you had such a bad experience. I mentioned the problem with Chinese and old original connectors below (`Please note that the Chinese aliexpress connectors and some of the older connectors…`) in the same BOM section, but I probably should have made a note above the first time the connectors were mentioned and/or highlighted it somehow.

**Comment by rah2501** [comment]
The later text doesn't make clear that the connectors can't be used in positions except for the top rows.

I'm confused about the status of this merge request.  You commented on my problem but not the patch and haven't merged it, is there a problem with the patch?

**Comment by DmNosachev** [comment]
I just want to clarify a few things to improve the documentation. I haven’t modified Kinesis Advantage-1 or 2 for a long time; most of the keyboards I’ve modified are old, pre-Advantage ones.

1. Advantage-1 and Advantage-2 use Molex 39-53-2135, locking, contact pads on both (?) sides.
2. There are three types of straight connectors on older keyboards (unidentified brand, various colors):
    - contact pads on both sides;
    - contact pads on "long" (with 7 pins below) side;
    - contact pads on "short" (with 6 pins below) side, same as chinese connectors from Aliexpress;
    
Now, correct me if I'm wrong. The FFC cable has contacts on one side, but since the native Molex connectors (on top row, thumb cluster and keywell PCBs in case of Advantage-2) have contact pads on both (?) sides, you can simply turn the FFC cable over (not twist, but reconnect it on both sides).

In the case of connecting the top rows on keyboards with rubber buttons (i.e. prior to Advantage-2), nothing can be turned over, since we are connecting a membrane. For this reason, I made two footprints for the top row connectors. A connector with contact pads on both sides can be installed in any position, connectors with contacts on the short side — in external positions, connectors with contacts on the long side — only in the internal position.

I don't have any Molex 39-53-2135 connectors on hand at the moment, so I can't confirm if they have pads on both sides (and I can't figure it out from the datasheet). If they are single sided, then I’m wrong and I need to add second footprints similar to the top rows.

**Comment by rah2501** [comment]
> since the native Molex connectors (on top row, thumb cluster and keywell PCBs in case of Advantage-2) have contact pads on both (?) sides, you can simply turn the FFC cable over

I didn't think of this and got excited for a moment.  I tried reversing the cables but alas, no luck.

> If they are single sided

They are.  I got the multimeter out and tested continuity with probes on a pin exposed on the side of the Molex connector and a pad on the other end of the cable.  There's a connection with the cable inserted one way but not the other.

> I need to add second footprints similar to the top rows

Aye.  To enable the use of the Chinese connectors, that would be needed.

**Pull request merged**
